[vulnerability_criteria]
aliases = true
desc = true
check_direct_dependencies_only = true

[maintainability_criteria]
forbid_archived = true
forbid_deprecated = true
forbid_quarantined = true
forbid_yanked = true
check_direct_dependencies_only = true
